image: node:14

cache:
  paths:
    - build
    - node_modules

stages:
  - init
  - lint
  - build
  - release
  - deploy

init:
  stage: init
  script:
    npm install

eslint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build

gitlab_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+)?$/'
  script:
    - echo running release for $CI_COMMIT_TAG
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: 'Created using the release-cli'

deploy_ci:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - cd node_modules/@cloudflare/wrangler/ && npm run postinstall && cd -
    - CF_ACCOUNT_ID=$CF_WORKERS_ACCOUNT_ID_CI CF_API_TOKEN=$CF_WORKERS_TOKEN_CI npm run publish
