image: node:14

cache:
  paths:
    - build
    - node_modules

stages:
  - init
  - lint
  - build
  - deploy

init:
  stage: init
  script:
    npm install

eslint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build

deploy_ci:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - cd node_modules/@cloudflare/wrangler/ && npm run postinstall && cd -
    - CF_ACCOUNT_ID=$CF_WORKERS_ACCOUNT_ID_CI CF_API_TOKEN=$CF_WORKERS_TOKEN_CI npm run publish
