name = "app-ci"
type = 'webpack'
account_id = ''
route = ''
zone_id = ''
usage_model = ''
workers_dev = true
target_type = "webpack"

[env.prd]
name = "app"

[site]
bucket = "build"
entry-point = "workers-site"
